### ISSUE TITLE
i18n client/server side rendering bug: Navigator not defined on Server side

### ISSUE THREAD

**Issue by Strehk** [DeutscheModelUnitedNations/munify-chase#19]
I encountered a bug during build time with the main `layout.tsx` file. I post the build console log below.

This bug seems to be because of line 30 and 31 of layout.tsx:
```
const locale = detectLocale(baseLocale, locales, navigatorDetector);
loadLocale(locale);
```

I commented out the code and instead followed a Chat-GPT advise that suggested the following:
```
  let locale = baseLocale; // default to baseLocale
  if (typeof window !== "undefined") {
    // Check if window is defined to ensure running on client side
    locale = detectLocale(baseLocale, locales, navigatorDetector);
    loadLocale(locale);
  }
```

But this seems to be suitable only as a temporary solution since it might result in only the base locale being used.
Please inspect this error. The "use client"; directive unfortunately cannot be removed since it throws another error with i18n.

```
munify/chase/frontend on  participant-pages [!] via  v16.16.0 took 4s 
❯ npm run build

> frontend@0.1.0 build
> next build

(node:32048) [DEP_WEBPACK_MODULE_UPDATE_HASH] DeprecationWarning: Module.updateHash: Use new ChunkGraph API
(Use `node --trace-deprecation ...` to show where the warning was created)
- info Creating an optimized production build  
- info Compiled successfully
- info Linting and checking validity of types  
- info Collecting page data  
[    ] - info Generating static pages (0/13)(node:32127) ExperimentalWarning: buffer.Blob is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:32129) ExperimentalWarning: buffer.Blob is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
ReferenceError: navigator is not defined
    at navigator_e (/Users/tadestrehk/github/DMUN/munify/chase/frontend/.next/server/chunks/412.js:15941:65)
    at l (/Users/tadestrehk/github/DMUN/munify/chase/frontend/.next/server/chunks/412.js:15932:135)
    at Nr (/Users/tadestrehk/github/DMUN/munify/chase/frontend/.next/server/chunks/412.js:15932:88)
    at RootLayout (/Users/tadestrehk/github/DMUN/munify/chase/frontend/.next/server/chunks/718.js:196:54)
    at Je (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:121:272)
    at Je (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:127:11)
    at Z (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:128:91)
    at Ke (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:131:155)
    at Me (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:130:289)
    at Z (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:128:350)

Error occurred prerendering page "/_not-found". Read more: https://nextjs.org/docs/messages/prerender-error
ReferenceError: navigator is not defined
    at navigator_e (/Users/tadestrehk/github/DMUN/munify/chase/frontend/.next/server/chunks/412.js:15941:65)
    at l (/Users/tadestrehk/github/DMUN/munify/chase/frontend/.next/server/chunks/412.js:15932:135)
    at Nr (/Users/tadestrehk/github/DMUN/munify/chase/frontend/.next/server/chunks/412.js:15932:88)
    at RootLayout (/Users/tadestrehk/github/DMUN/munify/chase/frontend/.next/server/chunks/718.js:196:54)
    at Je (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:121:272)
    at Je (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:127:11)
    at Z (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:128:91)
    at Ke (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:131:155)
    at Me (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:130:289)
    at Z (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:128:350)
ReferenceError: navigator is not defined
    at navigator_e (/Users/tadestrehk/github/DMUN/munify/chase/frontend/.next/server/chunks/412.js:15941:65)
    at l (/Users/tadestrehk/github/DMUN/munify/chase/frontend/.next/server/chunks/412.js:15932:135)
    at Nr (/Users/tadestrehk/github/DMUN/munify/chase/frontend/.next/server/chunks/412.js:15932:88)
    at RootLayout (/Users/tadestrehk/github/DMUN/munify/chase/frontend/.next/server/chunks/718.js:196:54)
    at Je (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:121:272)
    at Je (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:127:11)
    at Z (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:128:91)
    at Ke (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:131:155)
    at Me (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:130:289)
    at Z (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:128:350)

Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
ReferenceError: navigator is not defined
    at navigator_e (/Users/tadestrehk/github/DMUN/munify/chase/frontend/.next/server/chunks/412.js:15941:65)
    at l (/Users/tadestrehk/github/DMUN/munify/chase/frontend/.next/server/chunks/412.js:15932:135)
    at Nr (/Users/tadestrehk/github/DMUN/munify/chase/frontend/.next/server/chunks/412.js:15932:88)
    at RootLayout (/Users/tadestrehk/github/DMUN/munify/chase/frontend/.next/server/chunks/718.js:196:54)
    at Je (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:121:272)
    at Je (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:127:11)
    at Z (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:128:91)
    at Ke (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:131:155)
    at Me (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:130:289)
    at Z (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:128:350)
ReferenceError: navigator is not defined
    at navigator_e (/Users/tadestrehk/github/DMUN/munify/chase/frontend/.next/server/chunks/412.js:15941:65)
    at l (/Users/tadestrehk/github/DMUN/munify/chase/frontend/.next/server/chunks/412.js:15932:135)
    at Nr (/Users/tadestrehk/github/DMUN/munify/chase/frontend/.next/server/chunks/412.js:15932:88)
    at RootLayout (/Users/tadestrehk/github/DMUN/munify/chase/frontend/.next/server/chunks/718.js:196:54)
    at Je (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:121:272)
    at Je (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:127:11)
    at Z (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:128:91)
    at Ke (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:131:155)
    at Me (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:130:289)
    at Z (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:128:350)
ReferenceError: navigator is not defined
    at navigator_e (/Users/tadestrehk/github/DMUN/munify/chase/frontend/.next/server/chunks/412.js:15941:65)
    at l (/Users/tadestrehk/github/DMUN/munify/chase/frontend/.next/server/chunks/412.js:15932:135)
    at Nr (/Users/tadestrehk/github/DMUN/munify/chase/frontend/.next/server/chunks/412.js:15932:88)
    at RootLayout (/Users/tadestrehk/github/DMUN/munify/chase/frontend/.next/server/chunks/718.js:196:54)
    at Je (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:121:272)
    at Je (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:127:11)
    at Z (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:128:91)
    at Ke (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:131:155)
    at Me (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:130:289)
    at Z (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:128:350)
ReferenceError: navigator is not defined
    at navigator_e (/Users/tadestrehk/github/DMUN/munify/chase/frontend/.next/server/chunks/412.js:15941:65)
    at l (/Users/tadestrehk/github/DMUN/munify/chase/frontend/.next/server/chunks/412.js:15932:135)
    at Nr (/Users/tadestrehk/github/DMUN/munify/chase/frontend/.next/server/chunks/412.js:15932:88)
    at RootLayout (/Users/tadestrehk/github/DMUN/munify/chase/frontend/.next/server/chunks/718.js:196:54)
    at Je (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:121:272)
    at Je (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:127:11)
    at Z (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:128:91)
    at Ke (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:131:155)
    at Me (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:130:289)
    at Z (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:128:350)

Error occurred prerendering page "/participant/resolutions". Read more: https://nextjs.org/docs/messages/prerender-error
ReferenceError: navigator is not defined
    at navigator_e (/Users/tadestrehk/github/DMUN/munify/chase/frontend/.next/server/chunks/412.js:15941:65)
    at l (/Users/tadestrehk/github/DMUN/munify/chase/frontend/.next/server/chunks/412.js:15932:135)
    at Nr (/Users/tadestrehk/github/DMUN/munify/chase/frontend/.next/server/chunks/412.js:15932:88)
    at RootLayout (/Users/tadestrehk/github/DMUN/munify/chase/frontend/.next/server/chunks/718.js:196:54)
    at Je (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:121:272)
    at Je (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:127:11)
    at Z (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:128:91)
    at Ke (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:131:155)
    at Me (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:130:289)
    at Z (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:128:350)

Error occurred prerendering page "/login/chair". Read more: https://nextjs.org/docs/messages/prerender-error
ReferenceError: navigator is not defined
    at navigator_e (/Users/tadestrehk/github/DMUN/munify/chase/frontend/.next/server/chunks/412.js:15941:65)
    at l (/Users/tadestrehk/github/DMUN/munify/chase/frontend/.next/server/chunks/412.js:15932:135)
    at Nr (/Users/tadestrehk/github/DMUN/munify/chase/frontend/.next/server/chunks/412.js:15932:88)
    at RootLayout (/Users/tadestrehk/github/DMUN/munify/chase/frontend/.next/server/chunks/718.js:196:54)
    at Je (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:121:272)
    at Je (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:127:11)
    at Z (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:128:91)
    at Ke (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:131:155)
    at Me (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:130:289)
    at Z (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:128:350)

Error occurred prerendering page "/login/participant". Read more: https://nextjs.org/docs/messages/prerender-error
ReferenceError: navigator is not defined
    at navigator_e (/Users/tadestrehk/github/DMUN/munify/chase/frontend/.next/server/chunks/412.js:15941:65)
    at l (/Users/tadestrehk/github/DMUN/munify/chase/frontend/.next/server/chunks/412.js:15932:135)
    at Nr (/Users/tadestrehk/github/DMUN/munify/chase/frontend/.next/server/chunks/412.js:15932:88)
    at RootLayout (/Users/tadestrehk/github/DMUN/munify/chase/frontend/.next/server/chunks/718.js:196:54)
    at Je (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:121:272)
    at Je (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:127:11)
    at Z (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:128:91)
    at Ke (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:131:155)
    at Me (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:130:289)
    at Z (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:128:350)
ReferenceError: navigator is not defined
    at navigator_e (/Users/tadestrehk/github/DMUN/munify/chase/frontend/.next/server/chunks/412.js:15941:65)
    at l (/Users/tadestrehk/github/DMUN/munify/chase/frontend/.next/server/chunks/412.js:15932:135)
    at Nr (/Users/tadestrehk/github/DMUN/munify/chase/frontend/.next/server/chunks/412.js:15932:88)
    at RootLayout (/Users/tadestrehk/github/DMUN/munify/chase/frontend/.next/server/chunks/718.js:196:54)
    at Je (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:121:272)
    at Je (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:127:11)
    at Z (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:128:91)
    at Ke (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:131:155)
    at Me (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:130:289)
    at Z (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:128:350)
ReferenceError: navigator is not defined
    at navigator_e (/Users/tadestrehk/github/DMUN/munify/chase/frontend/.next/server/chunks/412.js:15941:65)
    at l (/Users/tadestrehk/github/DMUN/munify/chase/frontend/.next/server/chunks/412.js:15932:135)
    at Nr (/Users/tadestrehk/github/DMUN/munify/chase/frontend/.next/server/chunks/412.js:15932:88)
    at RootLayout (/Users/tadestrehk/github/DMUN/munify/chase/frontend/.next/server/chunks/718.js:196:54)
    at Je (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:121:272)
    at Je (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:127:11)
    at Z (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:128:91)
    at Ke (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:131:155)
    at Me (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:130:289)
    at Z (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:128:350)

Error occurred prerendering page "/participant/voting". Read more: https://nextjs.org/docs/messages/prerender-error
ReferenceError: navigator is not defined
    at navigator_e (/Users/tadestrehk/github/DMUN/munify/chase/frontend/.next/server/chunks/412.js:15941:65)
    at l (/Users/tadestrehk/github/DMUN/munify/chase/frontend/.next/server/chunks/412.js:15932:135)
    at Nr (/Users/tadestrehk/github/DMUN/munify/chase/frontend/.next/server/chunks/412.js:15932:88)
    at RootLayout (/Users/tadestrehk/github/DMUN/munify/chase/frontend/.next/server/chunks/718.js:196:54)
    at Je (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:121:272)
    at Je (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:127:11)
    at Z (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:128:91)
    at Ke (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:131:155)
    at Me (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:130:289)
    at Z (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:128:350)

Error occurred prerendering page "/participant/speakers". Read more: https://nextjs.org/docs/messages/prerender-error
ReferenceError: navigator is not defined
    at navigator_e (/Users/tadestrehk/github/DMUN/munify/chase/frontend/.next/server/chunks/412.js:15941:65)
    at l (/Users/tadestrehk/github/DMUN/munify/chase/frontend/.next/server/chunks/412.js:15932:135)
    at Nr (/Users/tadestrehk/github/DMUN/munify/chase/frontend/.next/server/chunks/412.js:15932:88)
    at RootLayout (/Users/tadestrehk/github/DMUN/munify/chase/frontend/.next/server/chunks/718.js:196:54)
    at Je (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:121:272)
    at Je (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:127:11)
    at Z (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:128:91)
    at Ke (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:131:155)
    at Me (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:130:289)
    at Z (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:128:350)
ReferenceError: navigator is not defined
    at navigator_e (/Users/tadestrehk/github/DMUN/munify/chase/frontend/.next/server/chunks/412.js:15941:65)
    at l (/Users/tadestrehk/github/DMUN/munify/chase/frontend/.next/server/chunks/412.js:15932:135)
    at Nr (/Users/tadestrehk/github/DMUN/munify/chase/frontend/.next/server/chunks/412.js:15932:88)
    at RootLayout (/Users/tadestrehk/github/DMUN/munify/chase/frontend/.next/server/chunks/718.js:196:54)
    at Je (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:121:272)
    at Je (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:127:11)
    at Z (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:128:91)
    at Ke (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:131:155)
    at Me (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:130:289)
    at Z (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:128:350)

Error occurred prerendering page "/participant/dashboard". Read more: https://nextjs.org/docs/messages/prerender-error
ReferenceError: navigator is not defined
    at navigator_e (/Users/tadestrehk/github/DMUN/munify/chase/frontend/.next/server/chunks/412.js:15941:65)
    at l (/Users/tadestrehk/github/DMUN/munify/chase/frontend/.next/server/chunks/412.js:15932:135)
    at Nr (/Users/tadestrehk/github/DMUN/munify/chase/frontend/.next/server/chunks/412.js:15932:88)
    at RootLayout (/Users/tadestrehk/github/DMUN/munify/chase/frontend/.next/server/chunks/718.js:196:54)
    at Je (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:121:272)
    at Je (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:127:11)
    at Z (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:128:91)
    at Ke (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:131:155)
    at Me (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:130:289)
    at Z (/Users/tadestrehk/github/DMUN/munify/chase/frontend/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:128:350)
- info Generating static pages (13/13)

> Export encountered errors on following paths:
        /_not-found
        /login/chair/page: /login/chair
        /login/participant/page: /login/participant
        /page: /
        /participant/dashboard/page: /participant/dashboard
        /participant/resolutions/page: /participant/resolutions
        /participant/speakers/page: /participant/speakers
        /participant/voting/page: /participant/voting
```

**Comment by m1212e** [comment]
@TadeSF Please consider using markup code sections when posting logs/code. 
I know what causes this issue, will take a look soon, thanks for reporting
